### ISSUE TITLE
in `require': cannot load such file -- spree_promo (LoadError)

### ISSUE THREAD

**Issue by alanalvespi** [spree-contrib/spree_store_credit_payment_method#17]
when executing the command "bundle exec rails g spree_store_credits:install" in the terminal, I got the following  error 
~/.rvm/gems/ruby-2.1.2@global/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- spree_promo (LoadError)

Any help?

**Comment by athal7** [comment]
@alanalvespi can you include what the gemfile is in the project you are trying to install this in? i don't think there is anything about spree_promo in this repo

**Comment by alanalvespi** [comment]
@athal7 sure
gem 'spree_store_credits'

**Comment by JDutil** [comment]
You need to point to the git repo:
gem 'spree_store_credits', github: 'spree-contrib/spree_store_credit_payment_method'

I'll update the readme.

**Comment by alanalvespi** [comment]
Thank you @JDutil 
In addition I specified the branch: '2-3-stable' to make it work
