### ISSUE TITLE
spree::Admin::PaymentsController:Class (NoMethodError) on bundle exec install

### ISSUE THREAD

**Issue by Waylon87** [spree-contrib/spree_store_credit_payment_method#27]
I'm getting this error when trying to install the 2-3-stable branch running `bundle exec rails g spree_store_credits:install`

```
.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree_store_credit_payment_method-aecee00bf815/app/controllers/spree/admin/payments_controller_decorator.rb:35:in `<top (required)>': private method `prepend' called for Spree::Admin::PaymentsController:Class (NoMethodError)
```

I see where the error is generated. I just don't know why its getting it. 

Any help would be greatly appreciated.

**Comment by athal7** [comment]
This extension requires >= ruby 2.1.0 currently

**Comment by Waylon87** [comment]
Ahh. Thank you.
